
dictionary = {
 	'Nao': 'Não',
 	'Nâo': 'Não',
 	'nao': 'não',
 	'nâo': 'não',
	'vocÊ': 'você',
	'voce': 'você',
    'codigo': 'códigos',
    'FLutter': 'Flutter',
	'funçâo': 'função',
 	'relaçôes': 'relações',
 	'relaçao': 'relação',
 	'relaçâo': 'relação',
 	'Entâo': 'Então',
    'metodo': 'método',
    'nivel': 'nível',
    'execuçâo': 'execução',
 	'civilizaçâo': 'civilização',
 	'sâo': 'são',
    'proprio': 'próprio',
 	'materia': 'matéria',
 	'organizaçâo': 'organização',
 	'tendencia': 'tendência',
    'QUando': 'Quando',
    'variavel': 'variável',
}
